fix(make): ensures test image is built for kind setup
Executing `make kind-clusters` on clean environment results with error:

```sh
+ for cluster_name in "east" "west"
+ kind load docker-image --nodes east-control-plane --name east quay.io/maistra-dev/federation-controller:test
ERROR: image: "quay.io/maistra-dev/federation-controller:test" not present locally
make: *** [Makefile:42: kind-clusters] Error 1
```

as image tagged with `test` is not built.

This fix ensures that we built the image when `USE_LOCAL_IMAGE` is set
to true so kind setup can suceed.